### ISSUE TITLE
Can you provide the code for pre-taining the teacher model?

### ISSUE THREAD

**Issue by jokc28** [dwang181/active-mixup#4]
I am currently trying to reproduce your active mixup work because I was much inspired by your work. 
During the progress, I tried multiple times to load the state_dict() of well pretrained model on CIFAR10. 
However, I kept facing the problem of "RuntimeError: Error(s) in loading state_dict for VGG: Missing key(s) in state_dict:"
I did some googling but it didn't work out. 
It would be helpful if you could provide what code you used to pretrain the teacher model. 
Thanks in advance.

**Comment by dwang181** [comment]
Thanks very much for your question. First, I would recommend you check the shared VGG model in active-mixup/models/vgg.py which shows the detailed architecture for teacher/student models. Please note that this VGG is a reduced version for CIFAR-10 which contains shorter FC and input size is 32 by 32. Then, you may just follow conventional training setting, like batch size 128, learning rate 0.1, epoch more than 200 etc. If you still run into questions, please let me know.

**Comment by dwang181** [comment]
#1 Thanks very much for your question. First, I would recommend you check the shared VGG model in active-mixup/models/vgg.py which shows the detailed architecture for teacher/student models. Please note that this VGG is a reduced version for CIFAR-10 which contains shorter FC and input size is 32 by 32. Then, you may just follow conventional training setting, like batch size 128, learning rate 0.1, epoch more than 200 etc. If you still run into questions, please let me know.
